name: osint-rag

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: osint-rag-postgres
    environment:
      POSTGRES_DB: osint-rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - osint-rag_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  osint-rag_postgres_data:
